version: '3.8'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: deployment/Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      sh -c "poetry install --no-interaction --no-ansi &&
             echo 'GPU is available for PyTorch/TensorFlow.' &&
             jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''"